{
  "DisplayName": "import2",
  "Parameters": {
    "param1": "value1",
    "param2": "value2"
  },
  "DataSource": {
    "DisplayName": "DataSource2",
    "ObjectFactoryName": "ObjectFactoryName2",
    "Parameters": {
      "param1": "value1",
      "param2": "value2"
    },
    "Instance": {}
  },
  "DataAddins": [
    {
      "DisplayName": "Addin2",
      "ObjectFactoryName": "ObjectFactoryName2",
      "Parameters": {
        "param1": "value1",
        "param2": "value2"
      },
      "Instance": {}
    }
  ]
}